version: '3.8'

services:
  url-mini:
    image: sachinviru/url-mini:latest
    container_name: url-mini
    ports:
      - "5000:5000"
    networks:
      monitoring
    restart: unless-stopped
    lables:
      - "com.prometheus.scrape=true"
      - "com.prometheus.port=5000"
    networks:
      monitoring:
        external: true  