name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install -r app/requirements.txt 

      - name: Get version and short SHA
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "version=v$(git rev-list --count)" >>$GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t sachinviru/url-mini:${{ steps.vars.outputs.version }} .
          docker tag sachinviru/url-mini:${{ steps.vars.outputs.version }} sachinviru/url-mini:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push sachinviru/url-mini:${{ steps.vars.outputs.version }}
          docker push sachinviru/url-mini:latest

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: sachinviru/url-mini:${{ steps.vars.outputs.version }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Scan the code using SonarQube
        uses: sonarsource/sonarqube-scan-action@v1.0.0
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  
          SONAR_SCANNER_OPTS: "-X"

      - name: Prune old Docker tags (keep last 3)
        uses: otwld/dockerhub-tag-cleanup
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: sachinviru/url-mini
          keep: 3


#      - name: Sonar QualScanity Gate 
#        uses: sonarsource/sonarqube-quality-gate-action@master
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
             

